### ISSUE TITLE
Storybook UI

### ISSUE THREAD

**Issue by Nativeway** [richardeschloss/nuxt-stories#29]
I love what you done here!

Would it be possible to somehow implement storybooks UI here? I just think that they did a great job at it :)

**Comment by richardeschloss** [comment]
I think there are certain aspects I like also about storybook's UI, however, I think it can be completely subjective based on who uses it. I like how they use a tree navigation in the sidebar instead of the accordion. I think the font size could be larger in their UI, but maybe many users are already used to that font. I think their UI is React-based, when I would prefer it to be Vue-driven for the Nuxt framework. 

Personally, I think it would be good to have a separate branches (or a separate repo) for maintaining the different storybook themes. I believe they separate core from themes and addons, which I tend to like. I want to keep the core pretty lightweight so that way when people want to use it for dozens of projects, it gets set up asap, and then customizing it would take a bit more time. 

There are still things I like about my UI...I want the story *content* to be king (so the toggle button that expands the view to full window helps showcase their content really well). I think prev/next arrows would also be useful. 

As great as the storybook UI is, I think with a bit of effort, I think we can create something even better. Do you want to help contribute the "tree nav component"? It would live in the "/.stories/.components" folder in this project. (suggested git branch: feature/treeNav)

**Comment by SnooHD** [comment]
Wouldn't it be better if we could implement storybook its self?
I agree that an all-vue approach sounds neat but actually using storybook/ui could save a lot of time and maintenance overall.

**Comment by richardeschloss** [comment]
It would be neat if we can just list [@storybook/ui](https://www.npmjs.com/package/@storybook/ui) as a dev dependency and just use it. I have to read up on their docs to see how we would wire up stories (our Nuxt routes) into their UI.

**Comment by richardeschloss** [comment]
Update: I created a local branch `feat/storybook-ui` in my workspace, and I am finding this to be a bit more challenging than expected. When I try to import `@storybook/ui` per their docs, I'm unable to. I encounter "Cannot use import statement outside a module". It may be some configuration issue in my workspace, but I'm not sure why it's encountering this. The module I am trying to import is in the transpiled dist. I'm sure I'll figure out what's going on.

**Comment by richardeschloss** [comment]
Update: I remember why I created this module in the first place. storybook is overly complicated and tries to do way too much. I think it's a wonderful idea that has just been executed and documented very poorly. Enabling storybooking per project takes a really long time (~10 minutes for me), and the configuration is another headache to encounter. While I was able to get past the "import" issue, I kept facing other issues because their documentation on using the ui API is fragmented and isn't maintained well.  I get concerned when published example code contains typos, isn't linted, and/or no longer existant. The @storybook/ui adds a lot of bloat for the Vue developer and causes builds and load times to slow significantly (this is before any stories are even created). 

The goal with this project is to be lightweight, easy to use and fast to configure. One line in the nuxt.config and that's it.

Yes, there are some aspects of the current storybook UI that I think are awesome, but I think aspects of that UI can be brought in to the sample stories and implemented without all the overhead that comes with storybookjs.

The solution can be greatly simplified and I stick to my original assessment.
