### ISSUE TITLE
Error with auto importing from '@/components'

### ISSUE THREAD

**Issue by ponnex** [richardeschloss/nuxt-stories#70]
![Screen Shot 2020-12-28 at 11 29 49 AM](https://user-images.githubusercontent.com/10062054/103187710-782d6280-4900-11eb-9f64-60bb3f8ca588.png)

I've followed the docs for the setup but I have the following issue on console.

This is how my components is structured since I'm following an atomic design style structure

![Screen Shot 2020-12-28 at 11 35 26 AM](https://user-images.githubusercontent.com/10062054/103187784-cb9fb080-4900-11eb-815a-0afee61f0ff4.png)

**Comment by richardeschloss** [comment]
Hi, thanks for reporting the bug. 

Here is the code that auto imports:
https://github.com/richardeschloss/nuxt-stories/blob/738332c93d79a223963db0c30e81d6388ae699ad/lib/plugin.register.js#L29

And here is the autoImport code:
https://github.com/richardeschloss/nuxt-stories/blob/738332c93d79a223963db0c30e81d6388ae699ad/lib/utils/autoImport.js#L9

In your workspace, this would be in node_modules/nuxt-stories/lib/utils/autoImport.js 

What version of Nuxt and Vue are you using? Are there js/vue files in the sub directories? What happens if you try to match this project's component's directory? Does it work if you have just "@/components/Hello.vue" ? And if so, does it break when introducing the subdirectories?

I have a few guesses as to what might be going on.

**Comment by ponnex** [comment]
Hello thank you for the quick response, I know it is related to components so I've tried adding just "Hello.vue" component earlier before and remove all other inside components folder but still have the same issue. I'm using nuxt 2.14.11 in typescript

**Comment by ponnex** [comment]
I've tried digging into the source code and found that in `autoImport` we're trying to import component in `@/components` folder via `Vue.components()`. Do we still need it given that Nuxt already has auto component import? [@nuxt/components](https://github.com/nuxt/components) or nuxt-stories import them differently?

**Comment by richardeschloss** [comment]
Hi, thank you for troubleshooting. Oh ok, I forgot they added that feature. I'll try it out on my end just to double check. I've been wanting to get rid of that line if I could. 

In case other people stumble on this, here's the Nuxt components reference: [components property](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-components/)

Since I don't want to steal your thunder or credit, do you want to submit the PR to branch [issue/70](https://github.com/richardeschloss/nuxt-stories/tree/issue/70)? (issue/70 --> issue/70). This way you should be able to get the "contributor" credit here.

The guidance would be
1) Delete this line:
https://github.com/richardeschloss/nuxt-stories/blob/738332c93d79a223963db0c30e81d6388ae699ad/lib/plugin.register.js#L29
2) Update the nuxt config:
```js
{
  ...
  components: true
  ...
```
3) Re-run the tests make sure things still pass with 100% cov:
```
npm run test:unit:cov
```

The smaller the changes, the better. (Even though other big changes would be nice, those will be saved for other issues)

**Comment by richardeschloss** [comment]
Hi @ponnex , please refer to branch [issue/70](https://github.com/richardeschloss/nuxt-stories/tree/issue/70) which contains working examples of code. It's important to understand that stories can be written in two ways: Vue-first or Markdown-first (markdown preferred). The nuxt.config "components" property will auto import only for the Vue-first stories, but the autoImport function will auto import for both Vue-first and Markdown-first stories. (actually, components property can be omitted and that branch still works)

In that branch, I have components in subdirectories and if you run that branch locally (npm run dev), you should be able to see the "oxygen" component at http://localhost:3000/stories/en/Examples/AutoImport  (this has both "Hello.vue" and "atoms/Oxygen.vue").

Please let me know how far this gets you. That branch just had dependencies updated and is using the JS build of Nuxt.
